# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmStateConfiguration',
            fields=[
                ('alarm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('alarm_state', models.CharField(choices=[('0', 'off'), ('1', 'on')], max_length=1)),
                ('client_state', models.CharField(choices=[('0', 'disconnected'), ('1', 'connected')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('door_state', models.CharField(choices=[('0', 'open'), ('1', 'closed')], max_length=1)),
                ('alarm_state', models.CharField(choices=[('0', 'off'), ('1', 'on')], max_length=1)),
                ('client_state', models.CharField(choices=[('0', 'disconnected'), ('1', 'connected')], max_length=1)),
            ],
        ),
    ]
