# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstateconfiguration',
            name='alarm_id',
        ),
        migrations.AddField(
            model_name='alarmstateconfiguration',
            name='alarm_name',
            field=models.CharField(default='primary', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
