# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='SMS', max_length=10)),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='messages sent')),
                ('remaining', models.PositiveIntegerField(default=0, verbose_name=' messages remaining')),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
