# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'get_latest_by': 'time'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
