# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='email@example.com', max_length=200),
            preserve_default=False,
        ),
    ]
