# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20170520_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
