# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_alert_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='message ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='messages remaining'),
        ),
    ]
