# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
