# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_auto_20170509_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
