# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_remove_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='alarm_state',
            field=models.CharField(blank=True, choices=[('0', 'off'), ('1', 'on')], max_length=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='client_state',
            field=models.CharField(blank=True, choices=[('0', 'disconnected'), ('1', 'connected')], max_length=1),
        ),
    ]
