# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_auto_20170514_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmstateconfiguration',
            name='alarm_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
