# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0009_alarmstateconfiguration_alarm_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmstateconfiguration',
            old_name='alarm_state',
            new_name='alarm_status',
        ),
    ]
